#!/bin/bash
apt update -y
apt install firewalld -y
firewall-cmd --zone=public --permanent --add-port=80/tcp
firewall-cmd --zone=public --permanent --add-port=443/tcp
firewall-cmd --zone=public --permanent --add-port=7080/tcp
firewall-cmd --reload
wget -O - http://rpms.litespeedtech.com/debian/enable_lst_debian_repo.sh | sudo bash
apt-get install lsphp74 -y
apt install lsphp74-common lsphp74-curl lsphp74-imap lsphp74-json lsphp74-mysql lsphp74-opcache lsphp74-imagick lsphp74-memcached lsphp74-redis -y
apt-get install openlitespeed -y
/usr/local/lsws/bin/lswsctrl start
cd /tmp
git clone https://github.com/Softicious/high-performance-production-server
cp high-performance-wordpress**/**httpd_config.conf /usr/local/lsws/conf/
cp high-performance-wordpress/vhconf.conf /usr/local/lsws/conf/vhosts/high-performance-production-server/
/usr/local/lsws/bin/lswsctrl restart
apt install redis -y
systemctl start redis-server
systemctl enable redis-server
cd /usr/local/lsws/
mv Example high-performance-production-server
chown -R nobody:nogroup /usr/local/lsws/high-performance-production-server/html
find /usr/local/lsws/high-performance-production-server/html/ -type d -exec chmod 750 {} \;
find /usr/local/lsws/high-performance-production-server/html/ -type f -exec chmod 640 {} \;
chown -R nobody:nogroup /usr/local/lsws/high-performance-production-server/html
